name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish package to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - name: Install Node Dependencies
        run: yarn install
      - name: Build node
        run: yarn build-node
      - name: Check package version
        run: yarn check-version
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}